import { task } from "hardhat/config";
import { writeFileSync } from "fs";
import { resolve } from "path";

interface Row {
  rule: string;
  kind: string;
  deployStrategy: bigint;
  deployDeposit: bigint;
  previewAccrual: bigint;
  depositCall: bigint;
  postInterest: bigint;
  withdraw: bigint;
}

const SECONDS_PER_DAY = 86400n;
const FROM_TS = 1_700_000_000n;
const TO_TS = FROM_TS + 360n * SECONDS_PER_DAY;
const PRINCIPAL = 1_000_000n;

async function deployStrategy(hre: any, kind: string): Promise<{ contract: any; gas: bigint }> {
  const { ethers } = hre;
  let f, c;
  switch (kind) {
    case "simple":
      f = await ethers.getContractFactory("SimpleStrategy");
      c = await f.deploy(350n, 0); break;
    case "compound":
      f = await ethers.getContractFactory("CompoundDailyStrategy");
      c = await f.deploy(300n, 1); break;
    case "tiered":
      f = await ethers.getContractFactory("TieredStrategy");
      c = await f.deploy([BigInt("1000000000000000000000000"), ethers.MaxUint256], [200n, 350n], 0); break;
    case "floating": {
      const o = await (await ethers.getContractFactory("MockRateOracle")).deploy(350, "ESTR");
      await o.waitForDeployment();
      f = await ethers.getContractFactory("FloatingStrategy");
      c = await f.deploy(await o.getAddress(), 50, 0, -10001, 10001); break;
    }
    case "kpi-linked": {
      const o = await (await ethers.getContractFactory("MockKpiOracle")).deploy(-25, "GHG");
      await o.waitForDeployment();
      f = await ethers.getContractFactory("KpiLinkedStrategy");
      c = await f.deploy(await o.getAddress(), 400, -100, 100, 0); break;
    }
    case "two-track":
      f = await ethers.getContractFactory("TwoTrackStrategy");
      c = await f.deploy(350, 5000, 5000, 1000, 0); break;
    default:
      throw new Error(`unknown kind ${kind}`);
  }
  await c.waitForDeployment();
  const tx = c.deploymentTransaction();
  const rcpt = await tx!.wait();
  return { contract: c, gas: rcpt!.gasUsed };
}

async function bench(hre: any, rule: string, kind: string): Promise<Row> {
  const { ethers, network } = hre;
  const [signer] = await ethers.getSigners();
  const { contract: strat, gas: deployStrategyGas } = await deployStrategy(hre, kind);
  const stratAddr = await strat.getAddress();
  const previewAccrualGas = await strat.previewAccrual.estimateGas(PRINCIPAL, FROM_TS, TO_TS);

  const usdc = await (await ethers.getContractFactory("MockERC20")).deploy("USDC", "USDC", 6);
  await usdc.waitForDeployment();
  await (await usdc.transfer(signer.address, PRINCIPAL * 10n)).wait();

  const reg = await (await ethers.getContractFactory("RuleRegistry")).deploy(signer.address);
  await reg.waitForDeployment();
  const ruleId = ethers.encodeBytes32String(rule.slice(0, 31));
  await (await reg.register(ruleId, stratAddr, ethers.ZeroHash)).wait();

  const fac = await (await ethers.getContractFactory("DepositFactory")).deploy(await reg.getAddress());
  await fac.waitForDeployment();

  const dtx = await fac.deploy(ruleId, await usdc.getAddress(), signer.address, false, 0);
  const drcpt = await dtx.wait();
  const deployDepositGas = drcpt!.gasUsed;
  let depositAddr = "?";
  for (const log of drcpt!.logs) {
    try {
      const parsed = fac.interface.parseLog(log);
      if (parsed?.name === "DepositDeployed") { depositAddr = parsed.args.deposit; break; }
    } catch {}
  }
  const dep = await ethers.getContractAt("InterestBearingDeposit", depositAddr);

  await (await usdc.approve(depositAddr, PRINCIPAL)).wait();
  const depositCallGas = (await (await dep.deposit(PRINCIPAL)).wait())!.gasUsed;

  await network.provider.send("evm_increaseTime", [Number(360n * SECONDS_PER_DAY)]);
  await network.provider.send("evm_mine");
  const postInterestGas = (await (await dep.postInterest()).wait())!.gasUsed;
  const withdrawGas = (await (await dep.withdraw(PRINCIPAL / 2n)).wait())!.gasUsed;

  return { rule, kind, deployStrategy: deployStrategyGas, deployDeposit: deployDepositGas, previewAccrual: previewAccrualGas, depositCall: depositCallGas, postInterest: postInterestGas, withdraw: withdrawGas };
}

const fmt = (n: bigint) => n.toLocaleString("en-US");

function renderResultsMd(rows: Row[]): string {
  const ts = new Date().toISOString();
  const out: string[] = [];
  out.push("# Gas benchmarks");
  out.push("");
  out.push("Generated by `npx hardhat bench` (or `npm run bench`) against Hardhat in-memory EVM (paris target, optimizer runs=200).");
  out.push("");
  out.push(`Last run: ${ts}`);
  out.push("");
  out.push("Numbers are real `gasUsed` from receipts (deployment + state-changing) and `eth_estimateGas` (view).");
  out.push("");
  out.push("## Per-strategy (1M USDC, 360 days)");
  out.push("");
  out.push("| Rule | Kind | Deploy strategy | Deploy deposit | previewAccrual | deposit() | postInterest() | withdraw() |");
  out.push("|---|---|---:|---:|---:|---:|---:|---:|");
  for (const r of rows) out.push(`| \`${r.rule}\` | ${r.kind} | ${fmt(r.deployStrategy)} | ${fmt(r.deployDeposit)} | ${fmt(r.previewAccrual)} | ${fmt(r.depositCall)} | ${fmt(r.postInterest)} | ${fmt(r.withdraw)} |`);
  out.push("");
  out.push("## Headline");
  out.push("");
  const cheap = rows.reduce((a, b) => a.previewAccrual < b.previewAccrual ? a : b);
  const dear = rows.reduce((a, b) => a.previewAccrual > b.previewAccrual ? a : b);
  out.push(`- Cheapest preview: \`${cheap.rule}\` (${cheap.kind}) — ${fmt(cheap.previewAccrual)} gas`);
  out.push(`- Most expensive preview: \`${dear.rule}\` (${dear.kind}) — ${fmt(dear.previewAccrual)} gas`);
  out.push(`- Average postInterest: ${fmt(rows.reduce((s, r) => s + r.postInterest, 0n) / BigInt(rows.length))} gas`);
  out.push(`- Average strategy deployment: ${fmt(rows.reduce((s, r) => s + r.deployStrategy, 0n) / BigInt(rows.length))} gas`);
  out.push("");
  out.push("## Notes (data-derived)");
  out.push("");
  const byKind: Record<string, Row> = Object.fromEntries(rows.map((r) => [r.kind, r]));
  if (byKind.simple && byKind.compound) {
    const ratio = (Number(byKind.compound.previewAccrual) / Number(byKind.simple.previewAccrual)).toFixed(2);
    out.push(`- \`compound\` preview is ${ratio}× \`simple\` (rpow over wad-scaled \`(1+r/n)^days\`).`);
  }
  for (const k of ["floating", "kpi-linked", "tiered", "two-track"] as const) {
    if (byKind.simple && byKind[k]) {
      const overhead = byKind[k].previewAccrual - byKind.simple.previewAccrual;
      const sign = overhead >= 0n ? "+" : "";
      const note = k === "tiered" ? " (2 bands; scales linearly)"
                : k === "floating" ? " (one external CALL to rate oracle)"
                : k === "kpi-linked" ? " (one external CALL to KPI oracle)"
                : " (one extra multiply by hardPortionBps)";
      out.push(`- \`${k}\` adds ${sign}${fmt(overhead)} gas vs \`simple\`${note}.`);
    }
  }
  out.push("- `postInterest` cost = inner accrual + storage writes to `accruedInterest` and `principal`.");
  const minD = rows.reduce((m, r) => r.deployStrategy < m ? r.deployStrategy : m, rows[0].deployStrategy);
  const maxD = rows.reduce((m, r) => r.deployStrategy > m ? r.deployStrategy : m, 0n);
  out.push(`- Strategy deployment ranges ${fmt(minD)} – ${fmt(maxD)} gas.`);
  out.push(`- \`Deploy deposit\` (factory call) ~${fmt(byKind.simple?.deployDeposit ?? 0n)} gas regardless of strategy.`);
  out.push("");
  out.push("## Companion artifact");
  out.push("");
  out.push("`hardhat-gas-reporter` output via `REPORT_GAS=true npm test` is uploaded as a separate CI artifact.");
  return out.join("\n") + "\n";
}

task("bench", "Run gas benchmarks for all 6 strategy kinds and write RESULTS.md")
  .setAction(async (_args, hre: any) => {
    console.log(`[bench] starting on ${hre.network.name}...\n`);
    const cases = [
      { rule: "simple-act360-eur-350", kind: "simple" },
      { rule: "compound-daily-eur-300", kind: "compound" },
      { rule: "tiered-corp-eur", kind: "tiered" },
      { rule: "floating-estr-plus-50", kind: "floating" },
      { rule: "esg-kpi-linked", kind: "kpi-linked" },
      { rule: "two-track-ecr-50-50", kind: "two-track" },
    ];
    const rows: Row[] = [];
    for (const c of cases) {
      const r = await bench(hre, c.rule, c.kind);
      console.log(`  ${c.rule.padEnd(28)} kind=${c.kind.padEnd(11)} preview=${fmt(r.previewAccrual).padStart(8)} post=${fmt(r.postInterest)}`);
      rows.push(r);
    }
    const md = renderResultsMd(rows);
    const path = resolve("RESULTS.md");
    writeFileSync(path, md);
    console.log(`\n[bench] wrote ${path} (${md.length} bytes, ${rows.length} rules)`);
  });
